export enum ActionTypes {
    KEYWORD_CLICK,
    CMS_SUBMIT,
    ENTRY_DRIVER_CONNECT,
    ENTRY_DRIVER_DISCONNECT,
    KEYWORD_DRIVER_CONNECT,
    BLOG_MOUNTED,
    PREV_PAGE,
    NEXT_PAGE,
    PAGE_CLICK,
    ENTRIES_RESET
}